apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapRoles: | 
    - rolearn: arn:aws:iam::056244392644:role/Github-actions-ECRAccess
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:masters