name: ci-test

on:
    workflow_dispatch:

    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env: 
          POSTGRES_PASSWORD: postgres_nobel
          POSTGRES_USER: postgres_nobel
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 30s
          --health-timeout 10s
          --health-retries 5
          
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21' # Update to a modern Go version

    - name: Checkout code into the Go module directory
      uses: actions/checkout@v3

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.3/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate.linux-amd64 /usr/bin
        which migrate

    - name: Install dependencies
      working-directory: simple_bank
      run: |
        go mod download
        go mod verify

    - name: Run migrations
      working-directory: simple_bank
      run: make migrateup

    - name: Run tests
      working-directory: simple_bank
      run: make test