name: ci-test

on:
    workflow_dispatch:

    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21' # Update to a modern Go version

    - name: Install dependencies
      working-directory: simple_bank
      run: |
        go mod download
        go mod verify

    - name: Run tests
      working-directory: simple_bank
      run: make test