name: Deploy to production

on:
    workflow_dispatch:
    push:
        branches: [main]
permissions:
  id-token: write
  contents: read

jobs:
  
  deploy:
    name: Build image
    runs-on: ubuntu-latest
     
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.33.4' # default is latest stable
        id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::056244392644:role/Github-actions-ECRAccess
          aws-region: eu-west-1
 
   
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          aws-region: eu-west-1
      
      - name: Load secrets and save to app.env
        working-directory: simple_bank
        run: aws secretsmanager get-secret-value --secret-id simple_bank --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env


      - name: Build, tag, and push docker image to Amazon ECR
        working-directory: simple_bank
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: simplebank
          IMAGE_TAG: ${{ github.sha }}
        run: |          
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
          docker push -a $REGISTRY/$REPOSITORY 

      - name: Update kube config
        run: |
          aws eks update-kubeconfig --name simple-bank --region eu-west-1  
          kubectl config get-contexts
          kubectl config use-context arn:aws:eks:eu-west-1:056244392644:cluster/simple-bank

      - name: Verify cluster access
        run: |
          kubectl config view
          sudo mkdir -p $HOME/.kube
          sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
          sudo chown $(id -u):$(id -g) $HOME/.kube/config
          kubectl get nodes

      - name: Deploy image to AWS EKS
        working-directory: simple_bank
        run: |
          
          kubectl apply -f eks/deployment.yaml --validate=false
          kubectl apply -f eks/svc.yaml --validate=false
          kubectl apply -f eks/ingress.yaml --validate=false
          
